### ISSUE TITLE
MediaPlayerDevice is deprecated

### ISSUE THREAD

**Issue by DarkWolf7** [jdeath/SageTVHomeassistant#1]
I'm getting the following error in the HA log:

MediaPlayerDevice is deprecated, modify SageTV to extend MediaPlayerEntity 

It seems that the the object was just renamed so it should be easy to just rename it to the new object name and it should work just fine.

I love the component btw! works like magic.

**Comment by jdeath** [comment]
Glad you like it. I was going to attempt to fix this eventually. Haven’t
gotten to it yet.

**Comment by jdeath** [comment]
Should be fixed. Thank you for pointing me to the fix.
