### ISSUE TITLE
SageTV V9.2 64 BIT?

### ISSUE THREAD

**Issue by RJ-Make** [jdeath/SageTVHomeassistant#3]
Will this work with SageTV 9.2 64 bit? I don't see a sagex folder?

**Comment by jdeath** [comment]
I still run 9.2 32 bit, but I do not see why it would not work on 64 bit.

You need to install the SageTV Sagex API plugin. Maybe also install the sagex services plugin, maybe the neilm webserver too. Not sure, it has been so long. That should give you the sagex folder.

**Comment by RJ-Make** [comment]
> I still run 9.2 32 bit, but I do not see why it would not work on 64 bit.
> 
> You need to install the SageTV Sagex API plugin. Maybe also install the sagex services plugin, maybe the neilm webserver too. Not sure, it has been so long. That should give you the sagex folder. 
> 
> 
> 

Thank you, I'll give it a try this week and see if I can get this working with the 64 bit version of SageTV.

Thanks for all your hard work!

**Comment by RJ-Make** [comment]
Update:

Error `Platform error sensor.sagetv - Integration 'sagetv' not found.` On HAOS configuration check. 

Under sensor.yaml

```
  - platform: sagetv
    scan_interval: 3600
    sagex: http://192.168.1.26:7070/
    posterdir: "/home/homeassistant/.homeassistant/www/posters/"
    posterurl: https://nabu.casa.link/local/posters/
```

**Comment by jdeath** [comment]
Did you download the sagetv folder from this repo, and put in your custom_components/ folder?

You probably need to restart homeassistant once before the HAOS check will work.

**Comment by RJ-Make** [comment]
> Did you download the sagetv folder from this repo, and put in your custom_components/ folder?
> 
> You probably need to restart homeassistant once before the HAOS check will work.

Thank you!

I created the folder and dropped the 2 listed files into the folder. However, this time I followed your instructions above and dropped the entire folder and it worked. 

Thank You.
